.MODEL SMALL
.STACK 100H
.DATA
VAR1 DB ?       ; DB = DEFINE BYTE
VAR2 DB ?       ; WE ARE DECLARING A UNINITIALIZED VARIABLE
RESULT DB ? 

.CODE                                                
MAIN PROC
    ;LETS INITIALIZE THE DATA SEGMENT 
    MOV AX,@DATA    ; @DATA = DATA SEGMENT NUMBER
    MOV DS,AX       ; DS = DATA SEGMENT REGISTER
    
    MOV AH,1
    INT 21H     
    MOV VAR1,AL
    SUB VAR1,30H  ;CONVERTING NUMERIC CHARACTER TO NUMERIC VALUE
    
    ;MOV AH,1
    INT 21H
    MOV VAR2,AL
    SUB VAR2,30H  ;CONVERTING NUMERIC CHARACTER TO NUMERIC VALUE
    
    ;NOW ADD THEM UP
    MOV BL,VAR1    ;BL = VAR1
    ADD BL,VAR2    ;BL = VAR1 + VAR2
    MOV RESULT,BL  ;RESULT = VAR1 + VAR2
    ADD RESULT,30H ;CONVERTING NUMERIC VALUE TO NUMERIC CHARACTER
    
    MOV AH,2
    MOV DL,RESULT
    INT 21H
    
    MOV AH,4CH
    INT 21H    
MAIN ENDP
    END MAIN