.MODEL SMALL
.STACK 100H
.DATA

.CODE 
MAIN PROC
    MOV AH,1
    INT 21H
    MOV BL,AL
    
    INT 21H
    MOV BH,AL
    
    INT 21H
    MOV DH,AL
    
    ;NOW ADD EM UP
    ADD BL,BH  ;BL = BL + BH  
    
    ;NOW SUB EM UP
    SUB BL,DH  ;BL = BL - DH
    
    ;NOW WE ARE NOT SUBTRACTING THE VALUE WITH ANY CONSTANT BECAUSE IT IS SELF CONVERTED INTO DECIMAL AS 30H + 30H - 30H = 30H
    
    MOV AH,2
    MOV DL,BL
    INT 21H 
       
    MOV AH,4CH
    INT 21H
MAIN ENDP
    END MAIN