.MODEL SMALL
.STACK 100H
.DATA

.CODE
MAIN PROC
    MOV AH,1
    INT 21H     ; INPUTTER CHARACTER IS STORED IN AL
    MOV BL,AL
    
    ;NEWLINE
    MOV AH,2
    MOV DL,0AH  ; 0AH = NEWLINE
    INT 21H
    MOV DL,0DH  ; 0DH = CARRIAGE RETURN
    INT 21H
    
    MOV AH,2
    MOV DL,AL
    INT 21H
    
    MOV AH,4CH
    INT 21H  
MAIN ENDP   
    END MAIN